substitutions:
  # esp-c6
  name_esp32c6: ""
  friendly_name: ""
  api_key: ""
  # thread MTD
  openthread_tlv: ""
  openthread_force_dataset: "true"
  openthread_poll_period: "3000ms"
  ota_password: ""
  # TB6612
  name_TB6612: ""
  pin_pwm: ""
  pin_in1: ""
  pin_in2: "" 
  speed_count: "100"
  # switch
  pin_stby: ""
  name_stby: ""
  # max17043_1 es: batteria per esp
  name_max17043_1: ""
  pin_sda_1: ""
  pin_scl_1: ""
  # max17043_2 es:batteria per motore
  name_max17043_2: ""
  pin_sda_2: ""
  pin_scl_2: ""


packages:

  board:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: boards/esp32-c6.yaml
    refresh: 1d

  core:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: core/thread_MTD_config.yaml
    refresh: 1d

  tb6612: 
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: sensors/TB6612/TB6612.yaml
    refresh: 1d

  max17043_1:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: sensors/MAX17043/MAX17043.yaml
    refresh: 1d
    substitutions:
      name_max17043: ${name_max17043_1}
      pin_sda: ${pin_sda_1}
      pin_scl: ${pin_scl_1}

  max17043_2:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: sensors/MAX17043/MAX17043.yaml
    refresh: 1d
    substitutions:
      name_max17043: ${name_max17043_2}
      pin_sda: ${pin_sda_2}
      pin_scl: ${pin_scl_2}

# pulsante per spegnere il motore
switch:
  - platform: gpio
    pin: ${pin_stby} 
    name: "${name_stby}"
    id: global_stby
    restore_mode: ALWAYS_ON

  