substitutions:
  id_max17043: ""
  name_max17043: ""
  i2c_id: ""

sensor:
  - platform: max17043
    id: ${id_max17043}
    i2c_id: ${i2c_id}
    battery_voltage:
      name: "Battery Voltage ${name_max17043}"
    battery_level:
      name: "Battery ${name_max17043}"
