substitutions:
  name: ""
  friendly_name: ""
  api_key: ""
  openthread_tlv: ""
  openthread_force_dataset: "true"
  ota_password: ""

packages: 

  board:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: boards/esp32-c6.yaml
    refresh: 1d

  core:
    url: https://github.com/perni24/esp_home_script.git
    ref: main
    file: core/thread_FTD_config.yaml
    refresh: 1d

  
